### ISSUE TITLE
Bug with latest beta 2

### ISSUE THREAD

**Issue by Addonman** [alarofrunetotem/ChampionCommander#16]
Error occured in: Global
Count: 2
Message: ..\AddOns\ChampionCommander\missionlist.lua line 317:
   attempt to index field 'allArtifactPower' (a nil value)
Debug:
   [C]: ?
   ChampionCommander\missionlist.lua:317:
      ChampionCommander\missionlist.lua:314
   (tail call): ?
   [C]: ?
Error occured in: Global
Count: 31
Message: ..\AddOns\ChampionCommander\cache.lua line 402:
   attempt to index field 'allArtifactPower' (a nil value)
Debug:
   [C]: ?
   ChampionCommander\cache.lua:402:
      ChampionCommander\cache.lua:378
   ChampionCommander\cache.lua:434: Reward2Class()
   ChampionCommander\cache.lua:483:
      ChampionCommander\cache.lua:479
   ChampionCommander\matchmaker.lua:581: Match()
   ChampionCommander\matchmaker.lua:694: ?()
   ChampionCommander\missionlist.lua:543:
      ChampionCommander\missionlist.lua:527
   (tail call): ?
   ChampionCommander\missionlist.lua:572: ReloadMissions()
   ChampionCommander\missionlist.lua:756:
      ChampionCommander\missionlist.lua:736
   (tail call): ?
   [C]: ?
   [C]: Show()
   ..\FrameXML\UIParent.lua:2614: SetUIPanel()
   ..\FrameXML\UIParent.lua:2420: ShowUIPanel()
   ..\FrameXML\UIParent.lua:2320:
      ..\FrameXML\UIParent.lua:2316
   [C]: SetAttribute()
   ..\FrameXML\UIParent.lua:3141:
      ..\FrameXML\UIParent.lua:3129
   [C]: ShowUIPanel()
   ..\FrameXML\UIParent.lua:1724:
      ..\FrameXML\UIParent.lua:1090
   [C]: ?

It totally froze my pc for like  a min

**Comment by alar77** [comment]
ArtifactPower is no longer a thing, removed

**Comment by LordDeimos666** [comment]
@alar77 even with Beta3 tested on 2 account and different toon, the problem is still here on my side.

41x ChampionCommander\cache.lua:402: attempt to index field 'allArtifactPower' (a nil value)
ChampionCommander\cache.lua:402: in function <ChampionCommander\cache.lua:378>
ChampionCommander\cache.lua:434: in function `Reward2Class'
ChampionCommander\cache.lua:483: in function <ChampionCommander\cache.lua:479>
ChampionCommander\matchmaker.lua:581: in function `Match'
ChampionCommander\matchmaker.lua:694: in function `?'
ChampionCommander\missionlist.lua:540: in function <ChampionCommander\missionlist.lua:524>
(tail call): ?
ChampionCommander\missionlist.lua:569: in function `ReloadMissions'
ChampionCommander\missionlist.lua:753: in function <ChampionCommander\missionlist.lua:733>
(tail call): ?
[C]: ?
[C]: in function `Show'
FrameXML\UIParent.lua:2614: in function `SetUIPanel'
FrameXML\UIParent.lua:2420: in function `ShowUIPanel'
FrameXML\UIParent.lua:2320: in function <FrameXML\UIParent.lua:2316>
[C]: in function `SetAttribute'
FrameXML\UIParent.lua:3141: in function `ShowUIPanel'
FrameXML\UIParent.lua:1724: in function <FrameXML\UIParent.lua:1090>

Locals:
self = <table> {
 MAXLEVEL = <function> defined @ChampionCommander\ChampionCommander.lua:131
 modules = <table> {
 }
 CancelTimer = <function> defined @ElvUI\Libraries\AceTimer-3.0\AceTimer-3.0.lua:147
 IsBlacklisted = <function> defined @ChampionCommander\core.lua:165
 GetAverageLevels = <function> defined @ChampionCommander\cache.lua:945
 allEquipments = <table> {
 }
 RebuildMissionCache = <function> defined @ChampionCommander\cache.lua:932
 GetDataModule = <function> defined @ChampionCommander\data.lua:14
 ActivateButton = <function> defined @ChampionCommander\core.lua:199
 GetDifficultyColors = <function> defined @ChampionCommander\core.lua:226
 GetMissionlistModule = <function> defined @ChampionCommander\missionlist.lua:16
 SetDefaultModulePrototype = <function> defined @ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:440
 MAXQUALITY = <function> defined @ChampionCommander\ChampionCommander.lua:134
 GetResources = <function> defined @ChampionCommander\cache.lua:745
 GetCacheModule = <function> defined @ChampionCommander\cache.lua:16
 IsEnabled = <function> defined @ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:482
 GetCompletedMissionData = <function> defined @ChampionCommander\autocomplete.lua:569
 MarkAsSeen = <function> defined @ChampionCommander\core.lua:289
 ReloadMissions = <function> defined @ChampionCommander\missionlist.lua:562
 RegisterMessage = <function> defined @ElvUI\Libraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
 UnregisterMessage = <function> defined @ElvUI\Libraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:179
 Pulse = <function> defined @ChampionCommander\missionlist.lua:638
 hooks = <table> {
 }
 db = <table> {
 }
 PauseApply = <function> defined @ChampionCommander\missionlist.lua:491
 Apply = <function> defined @ChampionCommander\missionlist.lua:494
 SetEnabledState = <function> defined @ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:455
 Hook = <function> defined @ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:274
 EmptyPermutations = <function> defined @ChampionCommander\cache.lua:850
 PushRefresher = <function> defined @ChampionCommander\missionlist.lua:553
 Reserve = <function> defined @ChampionCommander\ChampionCommander.lua:207
 Reward2Class = <function> defined @ChampionCommander\cache.lua:431
 ColorFromBias = <function> defined @ChampionCommander\ChampionCommander.lua:143
 NeedsTutorial = <function> defined @ChampionCommander\tutorials.lua:411
 ShowPermutations = <function> defined @ChampionCommander\missionpage.lua:289
 OnInitialized = <function> defined @ChampionCommander\core.lua:142
 GetMissionpageModule = <function> defined @ChampionCommander\missionpage.lua:16
 NewModule = <function> defined @ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:266
 GetMembersFrame = <function> defined @ChampionCommander\missionlist.lua:816
 SortTroop = <function> defined @ChampionCommander\cache.lua:815
 CleanPermutations = <function> defined @ChampionCommander\missionlist.lua:389
 revision = "ad50597"
 Unban = <function> defined @ChampionCommander\ChampionCommander.lua:222
 GetSelectedParty = <function> defined @ChampionCommander\matchmaker.lua:652
 GetName = <function> defined @ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:310
 DumpPermutations = <function> defined @ChampionCommander\cache.lua:924
 name = "ChampionCommander"
 RefillParties = <function> defined @ChampionCommander\matchmaker.lua:

**Comment by LordDeimos666** [comment]
Ok i tried something, removing the reference on the if iteration in cache.lua regarding artifactpower solve the issue and the latest beta doesn't give anymore problem with it.

![cache lua](https://user-images.githubusercontent.com/21112906/46570377-65b36100-c963-11e8-93dc-852b9f3290ac.png)
