### ISSUE TITLE
Still calculation errors (Ankoan Tidehunters?)

### ISSUE THREAD

**Issue by steel-raven** [alarofrunetotem/ChampionCommander#35]
Hi there (you already hate me, right? XD). 

As described in my last ticket, I still encounter calculation issues for the success chance. 
And I think it has something to do with the new troop type that came with 8.2 (Ankoan Tidehunters). 

They act different than other troops:
1. They have 3 lives
2. Each life they lost/each mission you send them they get another ability on top

See this description: 

> These troops for your mission table have 3 abilities, although only one is unlocked to start with. They have 3 vitality and as you use them in missions they level up. Another ability is unlocked with each lost vitality/gained level until all are unlocked prior to their last mission. The abilities in order are, Melee Troop, Waterborne, and Alliance Veteran.
You get them by purchasing Troop Requisition from Speaker Utia once you hit revered with the Ankoan.
Once their health is depleted they can be recruited again like any other troop from Master Mathias Shaw

![WoWScrnShot_090819_105633](https://user-images.githubusercontent.com/54681027/64486068-ce1c5980-d228-11e9-940b-b7a601d22457.jpg)
![WoWScrnShot_090819_105651](https://user-images.githubusercontent.com/54681027/64486069-ce1c5980-d228-11e9-800d-713cb06fd49f.jpg)

**Comment by alar77** [comment]
:) I absolutely do not hate you, "Au contraire" i really appreciate people spending theur time doing screenshots and posting things here
That said, ChampionCommander does not calculat chance, but just build parties and asks blizzard engines.
Issue coud be that for troops I dont calculate on "every troop" but only one time for every kind of troop, so, if you have 2 of the same troop one with 3 vitality left and one with 2, cc only consider one of them because all troops were all the same. If ankoan have different stats depending on vitality, here you have the error.
Changing this will slow down a lot the engine, I could probably do effective calculation ony for this kind of troop, but I need to recruit them and do some tests
